#cloud-config
## vim: syntax=yaml
##
## This is the configuration syntax that the write_files module
## will know how to understand. encoding can be given b64 or gzip or (gz+b64).
## The content will be decoded accordingly and then written to the path that is
## provided.
##
## Note: Content strings here are truncated for example purposes.
write_files:
-   encoding: b64
    content: <base64 encoded pool password>
    owner: root:root
    path: /etc/condor/pool_password
    permissions: '0600'
